# Devcontainer image scaffold. Features in devcontainer.json still apply.
# Android cmdline-tools: bash scripts/install-android-cmdline-tools.sh --apply
# Licenses: no auto-license. HUMAN/ADB accept SDK licenses on the host.
FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_SDK_ROOT=/opt/android-sdk
