"""Thin adapter bodies synced from AGENTS.md. Edit AGENTS.md, then re-sync."""
from __future__ import annotations

from pathlib import Path

GENERATED = "<!-- Generated by scripts/lib/agent_adapters.py — edit AGENTS.md, then re-sync. -->"
POINTER_MAX_LINES = 28
POINTER_KEYS = frozenset({"gemini", "windsurf", "cline", "aider", "continue"})
ADAPTER_MAX_BYTES = {"copilot": 1024, "cline": 1024}

POINTER = """Read `AGENTS.md` first (source of truth), then `docs/START_HERE.md`.
Tour (any IDE): ask your agent to read `docs/help/TOUR.md`.
Commands: `docs/help/BATCH_COMMANDS.md` (Cursor: type `/tour` or `/bootstrap`).
Edit `AGENTS.md` only; then `bash scripts/bootstrap-lifecycle.sh --sync-adapters`.
Do not put project rules in this file."""

CURSOR_RULE = f"""---
description: Canonical agent spec pointer (synced from AGENTS.md)
alwaysApply: true
---

{GENERATED}

# Main (AGENTS.md adapter)

Read `AGENTS.md` before editing. It is the source of truth for architecture, gates, and session protocol.

## Test-first

Every feature task must include automated tests, or the feature spec must state why tests are not feasible and name the fallback validation command.

## Invariants

- FOSS MIT default; no proprietary SDKs on the FOSS production path
- Max 300 lines static data (UI + i18n), 150 lines pure logic
- Conventional Commits; never commit secrets or `.env`
- Sequential BUILD_PLAN before Parallel; 🔲 / ✅ / ❌ status markers
- Destructive ops (`git push`, production deploys) need `[HUMAN]` approval

## Commands

Run `bash scripts/verify.sh` before marking a BUILD_PLAN row complete.

`python3 scripts/agent-run.py validate-bootstrap --quick`
`python3 scripts/agent-run.py watch-agent-gates --once --autofix --scope auto`
`python3 scripts/agent-run.py smoke-sprint --require`
`python3 scripts/agent-run.py update-deps`
`python3 scripts/agent-run.py check-local-compute`
"""

CLAUDE = f"""{GENERATED}

# Claude Code instructions

This project uses `AGENTS.md` as the canonical agent specification. Read it first, then `docs/START_HERE.md` and `docs/CURSOR_MODES.md`.

## Test-first

Do not complete a feature task without corresponding tests, or an explicit justification plus fallback validation command in `docs/features/{{name}}.md` / `docs/spec.md`.

## Do

- Follow BUILD_PLAN Sequential then Parallel
- Run `python3 scripts/agent-run.py watch-agent-gates --once --autofix --scope auto` after AGENT steps
- After a sprint is all ✅, run `python3 scripts/agent-run.py smoke-sprint --require` before the next sprint
- Keep edits inside the active feature container

## Do not

- Commit secrets, `.env`, or skip hooks
- Push or deploy without human approval
- Blind-overwrite child `AGENTS.md` on template upgrade
"""

COPILOT = f"""{GENERATED}

# GitHub Copilot instructions

Canonical spec: `AGENTS.md`. Router: `docs/START_HERE.md`. Modes: `docs/CURSOR_MODES.md`.

- Test-first: every feature change ships tests or a written fallback validation command
- Type-safe boundaries; validate untrusted input
- Conventional Commits; no secrets in the tree
- Prefer vertical slices under `examples/{{stack}}/` plus `docs/features/{{name}}.md`
- Use 🔲 / ✅ / ❌ (not GitHub `- [ ]` checkboxes) on repo checklists
"""

GEMINI = f"""{GENERATED}

# Gemini / Antigravity pointer

{POINTER}

Never add real project rules here — Antigravity treats GEMINI.md as higher priority than AGENTS.md.
"""

WINDSURF = f"""---
trigger: always_on
---

{GENERATED}

# AGENTS.md pointer

{POINTER}
"""

CLINE = f"""{GENERATED}

# Cline / Roo pointer

{POINTER}
"""

AIDER = f"""{GENERATED}

# Aider conventions pointer

{POINTER}
"""

CONTINUE = f"""{GENERATED}

# Continue pointer

{POINTER}
"""

ADAPTERS: tuple[tuple[str, Path, str], ...] = (
    ("cursor_rules", Path(".cursor/rules/main.mdc"), CURSOR_RULE),
    ("claude", Path("CLAUDE.md"), CLAUDE),
    ("copilot", Path(".github/copilot-instructions.md"), COPILOT),
    ("gemini", Path("GEMINI.md"), GEMINI),
    ("windsurf", Path(".windsurf/rules/agents-pointer.md"), WINDSURF),
    ("cline", Path(".clinerules"), CLINE),
    ("aider", Path("CONVENTIONS.md"), AIDER),
    ("continue", Path(".continue/rules/agents.md"), CONTINUE),
)
