"""Write a /gates status markdown file (canvas when the Cursor dir exists)."""
from __future__ import annotations

import json
import os
from pathlib import Path

from gates_canvas_health import ci_status_one_liner, dirty_tree_one_liner, fix_banner

__all__ = [
    "canvas_dir",
    "ci_status_one_liner",
    "dirty_tree_one_liner",
    "fix_banner",
    "load_gate_rows",
    "markdown_report",
    "next_open_row",
    "stack_tier",
    "write_status",
]


def stack_tier(root: Path) -> tuple[str, str]:
    path = root / ".cursor" / "stack-selection.json"
    if not path.is_file():
        return "?", "?"
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return "?", "?"
    return str(data.get("stack") or "?"), str(data.get("distribution_tier") or "?")


def next_open_row(root: Path) -> str:
    path = root / "BUILD_PLAN.md"
    if not path.is_file():
        return "(no BUILD_PLAN.md)"
    lines = path.read_text(encoding="utf-8").splitlines()
    # Prefer LOCAL AGENT, then any AGENT (skip CLOUD on This Computer), then other.
    for prefer in ("LOCAL", "AGENT", "ANY"):
        for line in lines:
            stripped = line.strip()
            if not (stripped[:1].isdigit() or stripped.startswith("-")):
                continue
            if "🔲" not in line:
                continue
            if prefer == "LOCAL":
                if "[AGENT][LOCAL]" not in line:
                    continue
            elif prefer == "AGENT":
                if "[AGENT]" not in line or "[AGENT][CLOUD]" in line:
                    continue
            return stripped[:120]
    return "(no open rows)"


def markdown_report(root: Path, extra_rows: list[tuple[str, str]]) -> str:
    stack, tier = stack_tier(root)
    lines = [
        "# Gate status",
        "",
        f"- Stack: `{stack}`",
        f"- Tier: `{tier}`",
        f"- Next BUILD_PLAN row: {next_open_row(root)}",
        f"- {ci_status_one_liner(root)}",
        f"- {dirty_tree_one_liner(root)}",
        "",
        "| Gate | Result |",
        "| --- | --- |",
        *[f"| {name} | {result} |" for name, result in extra_rows],
        "",
    ]
    return "\n".join(lines)


def canvas_dir() -> Path | None:
    override = os.environ.get("CURSOR_CANVAS_DIR", "").strip()
    if override:
        path = Path(override)
        return path if path.is_dir() else None
    home = Path.home() / ".cursor" / "projects"
    if not home.is_dir():
        return None
    matches = [p / "canvases" for p in home.iterdir() if (p / "canvases").is_dir()]
    return matches[0] if len(matches) == 1 else None


def _canvas_source(rows: list[tuple[str, str]]) -> str:
    encoded = json.dumps([[n, r] for n, r in rows], ensure_ascii=False)
    return (
        'import { H1, Stack, Table, Text } from "cursor/canvas";\n\n'
        f"const ROWS: string[][] = {encoded};\n\n"
        "export default function GatesStatus() {\n"
        "  return (\n"
        "    <Stack gap={16}>\n"
        "      <H1>Gate status</H1>\n"
        '      <Text tone="secondary" size="small">\n'
        "        Generated by scripts/render-gates-status.sh\n"
        "      </Text>\n"
        '      <Table headers={["Gate", "Result"]} rows={ROWS} />\n'
        "    </Stack>\n"
        "  );\n"
        "}\n"
    )


def _with_sw_budget(root: Path, rows: list[tuple[str, str]]) -> list[tuple[str, str]]:
    try:
        from sw_cache_budget import summary_row
    except ImportError:
        return rows
    sw_row = summary_row(root)
    if sw_row is None or any(name == "sw-cache-budget" for name, _ in rows):
        return rows
    return [*rows, sw_row]


def load_gate_rows(root: Path) -> list[tuple[str, str]]:
    path = root / ".cursor" / "last-feature-gate.json"
    if not path.is_file():
        rows: list[tuple[str, str]] = [("render-gates-status", "Pass")]
    else:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            rows = [("last-feature-gate.json", "Fail")]
        else:
            rows = [(str(name), "Pass") for name in data.get("gates_passed") or []]
            stage = data.get("failed_stage")
            if stage:
                rows.append((str(stage), "Fail"))
            if not rows:
                rows = [("feature-gate", "Pass" if data.get("ok") else "Fail")]
    return _with_sw_budget(root, rows)


def write_status(root: Path, extra_rows: list[tuple[str, str]] | None = None) -> Path:
    rows = load_gate_rows(root) if extra_rows is None else _with_sw_budget(root, list(extra_rows))
    dest = root / ".cursor" / "gates-status.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(markdown_report(root, rows), encoding="utf-8", newline="\n")
    canvases = canvas_dir()
    if canvases is not None:
        (canvases / "gates-status.canvas.tsx").write_text(
            _canvas_source(rows), encoding="utf-8", newline="\n"
        )
    return dest
