"""Generate docs/features/{slug}.md stubs from a BUILD_PLAN row title."""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / "docs" / "features" / "_template.md"


def slugify(title: str) -> str:
    text = title.lower().strip()
    text = re.sub(r"\(#\d+\)\s*$", "", text).strip()
    out: list[str] = []
    for ch in text:
        if ch.isalnum():
            out.append(ch)
        elif ch in " -_/":
            if out and out[-1] != "-":
                out.append("-")
    return "".join(out).strip("-")[:48] or "feature"


def render(title: str, slug: str) -> str:
    base = TEMPLATE.read_text(encoding="utf-8")
    body = base.replace("{name}", slug)
    body = body.replace("_describe the happy path_", f"Ship: {title}")
    note = (
        f"\n## Source BUILD_PLAN row\n\n"
        f"- Title: {title}\n"
        f"- Generated by `python3 scripts/agent-run.py gen-feature-spec -- --title ...`\n"
    )
    if "## Notes" in body:
        body = body.replace("## Notes", note + "## Notes", 1)
    else:
        body = body.rstrip() + "\n" + note
    return body


def main() -> int:
    parser = argparse.ArgumentParser(description="BUILD_PLAN row → feature-spec stub")
    parser.add_argument("--title", required=True, help="BUILD_PLAN row text without checkbox")
    parser.add_argument("--slug", default=None)
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if not TEMPLATE.is_file():
        print(f"FAIL: missing {TEMPLATE}", file=sys.stderr)
        return 1
    slug = args.slug or slugify(args.title)
    dest = ROOT / "docs" / "features" / f"{slug}.md"
    if dest.exists() and not args.force:
        print(f"EXISTS: {dest.relative_to(ROOT).as_posix()} (pass --force to overwrite)")
        return 0
    content = render(args.title, slug)
    if args.dry_run:
        print(content)
        return 0
    dest.write_text(content, encoding="utf-8")
    print(f"Wrote {dest.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
