"""Write an /update-deps dry-run markdown file (canvas when Cursor dir exists)."""
from __future__ import annotations

import json
import os
from pathlib import Path

from gates_canvas import canvas_dir, stack_tier
from gradle_apply import apply_env_pins
from update_deps import discover_langs, gradle_fallback_message


def parse_upd_lines(text: str) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "->" in line or "→" in line:
            name = line.split()[0][:80]
            rows.append((name, line[:120]))
        elif line.lower().startswith("gradle"):
            rows.append(("gradle", line[:120]))
    return rows


def default_rows(root: Path) -> list[tuple[str, str]]:
    langs = discover_langs(root)
    rows: list[tuple[str, str]] = [("ecosystems", ", ".join(langs) or "none")]
    hint = gradle_fallback_message(root)
    if hint:
        rows.append(("gradle", hint[:120]))
    pins = os.environ.get("UPDATE_GRADLE_PINS", "")
    if pins:
        for line in apply_env_pins(root, pins, write=False):
            rows.append(("gradle-pin", line[:120]))
    extra = os.environ.get("UPD_DRY_RUN_TEXT", "")
    if extra:
        rows.extend(parse_upd_lines(extra))
    return rows


def markdown_report(root: Path, rows: list[tuple[str, str]]) -> str:
    stack, tier = stack_tier(root)
    lines = [
        "# Update-deps dry-run",
        "",
        f"- Stack: `{stack}`",
        f"- Tier: `{tier}`",
        "",
        "| Item | Detail |",
        "| --- | --- |",
    ]
    for name, detail in rows:
        lines.append(f"| {name} | {detail} |")
    lines.append("")
    return "\n".join(lines)


def _canvas_source(rows: list[tuple[str, str]]) -> str:
    encoded = json.dumps([[n, d] for n, d in rows], ensure_ascii=False)
    return (
        'import { H1, Stack, Table, Text } from "cursor/canvas";\n\n'
        f"const ROWS: string[][] = {encoded};\n\n"
        "export default function UpdDryRun() {\n"
        "  return (\n"
        "    <Stack gap={16}>\n"
        "      <H1>Update-deps dry-run</H1>\n"
        '      <Text tone="secondary" size="small">\n'
        "        Generated by scripts/render-upd-status.sh\n"
        "      </Text>\n"
        '      <Table headers={["Item", "Detail"]} rows={ROWS} />\n'
        "    </Stack>\n"
        "  );\n"
        "}\n"
    )


def write_status(root: Path, rows: list[tuple[str, str]] | None = None) -> Path:
    data = rows if rows is not None else default_rows(root)
    dest = root / ".cursor" / "upd-status.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(markdown_report(root, data), encoding="utf-8", newline="\n")
    canvases = canvas_dir()
    if canvases is not None:
        (canvases / "upd-dry-run.canvas.tsx").write_text(
            _canvas_source(data), encoding="utf-8", newline="\n"
        )
    return dest


def main() -> int:
    dest = write_status(Path.cwd())
    print(f"Wrote {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
