"""Hash real installer files and write a Winget stub. Never submit."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

PLACEHOLDER = "https://example.com/releases"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_manifest(
    out: Path,
    *,
    pkg_id: str,
    version: str,
    installers: list[tuple[str, Path, str]],
) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for arch, path, url in installers:
        rows.append(
            "\n".join(
                (
                    f"  - Architecture: {arch}",
                    "    InstallerType: zip",
                    f"    InstallerUrl: {url}",
                    f"    InstallerSha256: {sha256_file(path)}",
                )
            )
        )
    body = "\n".join(
        (
            "# Generated by winget-publish-loop.sh — do not submit until [HUMAN] replaces URLs",
            f"PackageIdentifier: {pkg_id}",
            f"PackageVersion: {version}",
            "PackageLocale: en-US",
            "Publisher: Example Publisher",
            "PackageName: Golden Path Example",
            "License: MIT",
            "ShortDescription: Local Winget loop output",
            "Installers:",
            *rows,
            "ManifestType: singleton",
            "ManifestVersion: 1.6.0",
            "",
        )
    )
    out.write_text(body, encoding="utf-8")
    return out


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Write a hashed Winget stub from installer files")
    parser.add_argument("--x64", type=Path, required=True)
    parser.add_argument("--arm64", type=Path, default=None)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--id", default="Foss.GoldenPath")
    parser.add_argument("--version", default="0.0.0")
    parser.add_argument("--url-base", default=PLACEHOLDER)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    missing = [str(args.x64)] if not args.x64.is_file() else []
    if args.arm64 is not None and not args.arm64.is_file():
        missing.append(str(args.arm64))
    if missing:
        print("FAIL: installer file(s) missing: " + ", ".join(missing))
        return 1
    installers = [
        ("x64", args.x64, f"{args.url_base}/{args.version}/{args.x64.name}"),
    ]
    if args.arm64 is not None:
        installers.append(("arm64", args.arm64, f"{args.url_base}/{args.version}/{args.arm64.name}"))
    path = write_manifest(args.out, pkg_id=args.id, version=args.version, installers=installers)
    print(f"Wrote {path}")
    print("[HUMAN] Replace InstallerUrl with GitHub Release HTTPS assets before microsoft/winget-pkgs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
